version: "3"
services:
  postgres_db:
    image: postgres:latest
    container_name: krupenin_nikolay_netology_db
    ports:
      - 5432:5432
    volumes:
      - ./pg_data:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_USER: NW
      POSTGRES_PASSWORD: krupenin123
      POSTGRES_DB: krupenin_na_db
      PGDATA: /var/lib/postgresql/data/pgdata
    networks:
      krupenin_nikolay_my_netology_hw:
        ipv4_address: 172.22.0.2
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    container_name: krupenin_na_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: krupenin_na@mail.me
      PGADMIN_DEFAULT_PASSWORD: 123
    ports:
      - 61231:80
    networks:
      krupenin_nikolay_my_netology_hw:
        ipv4_address: 172.22.0.3
    restart: always

  zabbix-server:
    image: zabbix/zabbix-server-pgsql
    links:
      - postgres_db
    container_name: krupenin_na_zabbix-netology
    environment:
      DB_SERVER_HOST: 172.22.0.2
      POSTGRES_USER: NW
      POSTGRES_PASSWORD: krupenin123
    ports:
      - 10051:10051
    networks:
      krupenin_nikolay_my_netology_hw:
        ipv4_address: 172.22.0.4
    restart: always

  zabbix_wgui:
    image: zabbix/zabbix-web-apache-pgsql
    links:
      - postgres_db
      - zabbix-server
    container_name: krupenin_na_netology-zabbix-frontend
    environment:
      DB_SERVER_HOST: 172.22.0.2
      POSTGRES_USER: NW
      POSTGRES_PASSWORD: krupenin123
      ZBX_SERVER_HOST: zabbix_wgui
      PHP_TZ: Europe/Moscow
    ports:
      - 80:8080
      - 443:8443
    networks:
      krupenin_nikolay_my_netology_hw:
        ipv4_address: 172.22.0.5
    restart: always

networks:
  krupenin_nikolay_my_netology_hw:
    driver: bridge
    ipam:
      config:
        - subnet: 172.22.0.0/29
